### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by docjojo** [l3rady/WordPress-APCu-Object-Cache#13]
Hi is there any chance for a new version?

**Comment by l3rady** [comment]
Funny you should mention I updated it about a month ago but didn't publish the changes as life got in the way. I have a composer file to add but you can consider https://github.com/l3rady/object-cache-apcu/pull/14 the update

**Comment by docjojo** [comment]
Thank you!
#14 still is v1.1 even with the changes?

Do you consider this version to be stable?

I have a "nice" stats function to add - if you like.

`    public function stats()
    {
        function bsize($s) { foreach (array('','K','M','G') as $i => $k) { if ($s < 1024) break; $s/=1024; } return sprintf("%5.1f %sB",$s,$k); };
    
        $bytes=0; $c=0;
        foreach ( $this->local_cache as $group => $cache ) 
        { $c++; $bytes+=(int) strlen(serialize($cache)); };
            
        $total=$this->cache_hits+$this->cache_misses+0.001;
        $hits=$this->cache_hits*100/$total;
        $misses=$this->cache_misses*100/$total;
    
        echo '<table>
        <tbody>
                <tr><td>Type:</td><td>APCu</td></tr>
                <tr><td>Used:</td><td>'.esc_html(bsize($bytes)).'</td></tr>
                <tr><td>Items:</td><td>'.esc_html(number_format($c)).'</td></tr>
                <tr><td>Hits:</td><td>'.esc_html(number_format($this->cache_hits).sprintf(" (%.1f%%)",$hits)).'</td></tr>
                <tr><td>Misses:</td><td>'.esc_html(number_format($this->cache_misses).sprintf(" (%.1f%%)",$misses)).'</td></tr>
                <tr><td colspan="2"><center style="font-size:60%; margin:0;">Hitrate</center><div class="ac_percent_div"><span class="ac_percent" style="width:'.esc_html(round($hits)).'%; background-color:green;"></span><span class="ac_percent" style="width:'.esc_html(round($misses)).'%; background-color:red;"></span></div></td></tr>
            </tbody>
        </table>';
    }`

**Comment by l3rady** [comment]
@docjojo I've pushed more updates. 1.2 is stable I will get it deployed to packagist.org soon before releasing it into main.

The stats just mirror what wp does: https://developer.wordpress.org/reference/classes/wp_object_cache/stats/

I'm not against improving the stats but if I was to change it I would rather pull details from APCu rather than localcache as there are times where that can be disabled.

**Comment by docjojo** [comment]
Woud be glad to be notified upon relase.
Many thanks.

**Comment by docjojo** [comment]
can not find it on packagist.org what will be the slug?

**Comment by l3rady** [comment]
hadn't published it yet, but just done it now: https://packagist.org/packages/l3rady/object-cache-apcu

**Comment by docjojo** [comment]
Great, thank you.
Thank you for your info!
Great work.
