### ISSUE TITLE
can not activate/deactivate plugins after object-cache.php installation

### ISSUE THREAD

**Issue by docjojo** [l3rady/WordPress-APCu-Object-Cache#15]
Hello Scott,

it is difficult to reproduce the issue, but sometimes i can not activate/deactivate plugins after object-cache.php installation.

i have used atec-cache-info plugin to flush the caches.
- apcu_clear_cache();
- $wp_object_cache->flush();
- opcache_reset();

after that, activate/deactivate worked, sometimes. in rare cases i had to remove object-cache.php to make activate/deactivate  work again.

did have any of this issue or an idea what could be the reason?

C.

**Comment by l3rady** [comment]
When using the plugin I've never had this issue. I don't use APCu cache anymore as I've scaled to multi instance and so have to use a network connected cache such as Redis or Memcached.

Are you running multiple instances as the behaviour you explained could be explained by that.

**Comment by docjojo** [comment]
thank you, no, it is a local single installation.

**Comment by docjojo** [comment]
Hello Scott, 
I am getting this error:
Warning: foreach() argument must be of type array|object, string given in /Users/DocJoJo/Sites/wordpress/wp-content/object-cache.php on line 992

the foreach loop

```
    public function get_multiple($keys, $group = 'default', $force = false)
    {
        $values = [];

        foreach ($keys as $key) {
            $values[$key] = $this->get($key, $group, $force);
        }

        return $values;
    }

```

**Comment by l3rady** [comment]
https://developer.wordpress.org/reference/functions/wp_cache_get_multiple/

The docs for the function expect an array so something in your site may not be using the function correctly. Do you have the full stack trace to see what is calling the function?

**Comment by docjojo** [comment]
will have to look how i can reproduce the issue, just wanted to let you know.

**Comment by docjojo** [comment]
Hello Scott, I do have the plugin issue on one of my sites.
are you willing to have a log at it?

**Comment by docjojo** [comment]
I still have this issue, that plugins can not be activated/deactivated and also on my dev machine, localhost, if I change the code of my plugin and reload, the code is not refreshed. If I run apcu_clear_cache();, it works, so it must have something to do with the APCu object cache.

**Comment by l3rady** [comment]
if code changes are not being picked up that sounds possibly like opcache is at fault, another caching plugin or something specific to do with your hosted environment. I'm not saying my plugin is at fault but there isn't concrete evidence that shows the plugin is at fault. To have a chance at being able to help you, I will need a proper bug report.

**Comment by docjojo** [comment]
sure, i am still try to reproduce the issue to give you something to look at.

**Comment by docjojo** [comment]
I can send you a login to one of my sites, if you have the time to have a look at it.

**Comment by nisbet-hubbard** [comment]
@docjojo, you said you were using `atec-cache-info`. Have you tried the same author’s other plugin atec Cache APCu? It provides l3rady’s `object-cache.php` but should offer better integration than `atec-cache-info`.

**Comment by docjojo** [comment]
@nisbet-hubbard 
I am the author of both atec plugins, the share the same code base.
