### ISSUE TITLE
Install as plugin

### ISSUE THREAD

**Issue by szepeviktor** [l3rady/WordPress-APCu-Object-Cache#2]
(without activation)

Please consider adding a WP.org style readme.txt so WP-CLi could install it.

``` bash
wp plugin install https://github.com/l3rady/WordPress-APCu-Object-Cache/archive/master.zip
ln -sv plugins/WordPress-APCu-Object-Cache-master/object-cache.php wp-content/
```

Thank you.

**Comment by szepeviktor** [comment]
A tool for you: https://github.com/wpreadme2markdown/wp-readme-to-markdown

**Comment by l3rady** [comment]
This object cache isn't a plugin and shouldn't really be placed in the plugins folder. The preferred method is to either manually add the drop in in the correct place or use composer and a dropin plugin installer to automatically place the drop in at build. I'm not planning on making this as a plugin as I think its bad security that WP/Plugins can write to filesystem other than in uploads.
