### ISSUE TITLE
Slower than no cache

### ISSUE THREAD

**Issue by Dreamsorcerer** [l3rady/WordPress-APCu-Object-Cache#6]
I have a small website, and these are the typical loading times I see logged:
no wp-content/object-cache.php: 59-63ms
Using this APCu object cache: 70-75ms

This is significantly slower than the default behaviour. I even tried making some trivial changes to improve code efficiency, such as using `global $wp_object_cache`, but I only managed to improve the speed to about 68-75ms.

By comparison, this Redis cache: https://wordpress.org/plugins/redis-cache/
Using that as a drop-in file (not as a plugin) gets me typical load times of 57-60ms.

APCu is supposed to be faster than Redis, so that suggests there is something inherently inefficient in this code when compared with the Redis plugin.

**Comment by AiratTop** [comment]
I agree, site with APCu-Object-Cache is working slower.

**Comment by l3rady** [comment]
In the limited testing that I have just done now, I cannot replicate the slow down you speak of.

I have just set up a fresh WP install with no plugins and tested the TTFB on the home page and find that the TTFB takes roughly about the same time using WP built-in array cache as my APCu cache.

To me, that seems normal on a fresh site as there isn't much to cache here so no gains to be had.

I then wanted to test the performance of my APCu object cache vs a Redis one off the plugin store and tested the speed of 100,000 get and set actions using this code. Redis was installed and running locally.

    $start = microtime(true);
    for ($i = 0; $i < 100000; $i++) {

        wp_cache_set('testing', [1, 2, 3], 'testing', 600);

    }
    $end = microtime(true);

    var_dump(  $end - $start);


    $start = microtime(true);
    for ($i = 0; $i < 100000; $i++) {

        wp_cache_get('testing', 'testing');

    }
    $end = microtime(true);

    var_dump(  $end - $start);

Both results on both object cache stores took around 1.2 seconds consistently and saw no major time differeneces between the two object caches.

Now neither of these tests are perfect but to me based on these results and on my experience of using this APCu plugin on many sites I cannot say I have ever seen performance issues with it. On the heavy content sites I run this on I always see massive improvements.

Now thats not to say that in certain scenarios APCu might not be the right fit. The built in object cache in wordpress stores its data in a local array and that will be quicker to retrieve from that calling APCu. If your database calls are fast and you don't store much in the object cache then I can see how this object cache could add some overhead.

If you want to shows some benchmarks where this plugin performs worse than others then I'd be happy to instigate further but looking through the code I'm not seeing where I can get gains in speed. Happy to be proved wrong though.

**Comment by AiratTop** [comment]
Maybe I have problems with right apcu settings. 
@l3rady Can you give some recommendations for me and [my site](https://airat.biz/en/)?

## My Configuration:

- BuddyPress
- bbPress
- WooCommerce 
- JetPack
- WordPress
- ... 50+ plugins 
(latest versions).

### VPS:

- Ubuntu 16.04
- RAM 2GB 
- SSD 15GB
- CPU 1 core 3800 MHz 
- PHP 7.1
- MySQL 5.7.23
- apache + nginx

## apcu.ini
```
extension=apcu.so

## Включаем
apc.enabled=1
apc.shm_segments=1

## Выделение памяти для APC
apc.shm_size=128M

## Время для кеширования PHP файлов - 1 час
apc.ttl=3600

## Время кеширования переменных и т.д.
apc.user_ttl=3600

## Сборка мусора через каждый час
apc.gc_ttl=3600

## Максимальный размер кешируемых файлов
apc.max_file_size=1M

## Проверка времени модификации скрипта
apc.stat=0
```

Now APCu is disabled (`apc.enabled=0`) and `object-cache.php` deleted

```
# dpkg -l | grep apcu -i
ii  php-apcu                          5.1.11+4.0.11-1+ubuntu16.04.1+deb.sury.org+1             amd64        APC User Cache for PHP
ii  php-apcu-bc                       1.0.4-1+ubuntu16.04.1+deb.sury.org+1                     amd64        APCu Backwards Compatibility Module
```


Does my `/etc/php/7.1/mods-available/apcu.ini` file looks good?

**Comment by Dreamsorcerer** [comment]
Well, that's interesting. Adding your test get/set code, these are the approximate load times I'm seeing:
Default: 100ms
APCu: 480ms
Redis: 1900ms

It would seem that the slow down I'm seeing is not being caused by get/set calls, but something else.

If you're timing TTFB with a remote tool, the results fluctuate too much to accurately see these speed variations. I'm using Nginx to log the time taken by fastcgi to handle the request, so I'm only looking at the PHP execution time.

**Comment by l3rady** [comment]
The get set calls test I did was very basic. it only tests setting a small array. Maybe setting larger values may see an issue.

Does APCu in your case have enough memory assigned to it? Correct me if I'm wrong but doesn't APCu dump all of its content if the memory it is assigned is exhausted?

**Comment by Dreamsorcerer** [comment]
I now have another site on my server from a new client. So, completely different setup and these are the rough execution times I'm seeing:
Default: ~190ms
Redis: ~175ms
APCu: ~330ms

So, definitely something going wrong with this cache.
As for memory, APCu memory usage during these tests is 1 MB out of 256 MB available.

**Comment by rob006** [comment]
This is because both, default `WP_Object_Cache` and redis cache plugin use a local variable to store cache used in particular request. This seems to be significantly faster than calling `apcu_fetch()`whenever you need a value from cache (in my case rendering posts list produces over 2k calls to APCu, after implementing local cache it is less than 200).

I opened PR to fix this (plus some minor improvements). @Dreamsorcerer can you try https://github.com/rob006/WordPress-APCu-Object-Cache/blob/patch-1/object-cache.php and check if you see any improvement?

**Comment by Dreamsorcerer** [comment]
On my home page, I get roughly:
Redis/default: ~120ms
Old APCu: ~128ms
Patched APCu: ~116ms

On my blog page, I get a more noticeable difference, with the new code running around 160ms (roughly the same as default and Redis), while the old code is around 200+ms.

So, looks promising. I tried running it on my client's site as well, but for some reason both the old and patched APCu versions are causing the site to produce a white screen, with no errors logged. Not sure what's happened there, still works with Redis or default.

**Comment by l3rady** [comment]
See https://github.com/l3rady/WordPress-APCu-Object-Cache/pull/8
